// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "snakealive/m/internal/services/trip/models"

	gomock "github.com/golang/mock/gomock"
)

// MockTripRepository is a mock of TripRepository interface.
type MockTripRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryMockRecorder
}

// MockTripRepositoryMockRecorder is the mock recorder for MockTripRepository.
type MockTripRepositoryMockRecorder struct {
	mock *MockTripRepository
}

// NewMockTripRepository creates a new mock instance.
func NewMockTripRepository(ctrl *gomock.Controller) *MockTripRepository {
	mock := &MockTripRepository{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepository) EXPECT() *MockTripRepositoryMockRecorder {
	return m.recorder
}

// AddAlbum mocks base method.
func (m *MockTripRepository) AddAlbum(ctx context.Context, album *models.Album, userID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAlbum", ctx, album, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAlbum indicates an expected call of AddAlbum.
func (mr *MockTripRepositoryMockRecorder) AddAlbum(ctx, album, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlbum", reflect.TypeOf((*MockTripRepository)(nil).AddAlbum), ctx, album, userID)
}

// AddLinkToCache mocks base method.
func (m *MockTripRepository) AddLinkToCache(ctx context.Context, uuid string, id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLinkToCache", ctx, uuid, id)
}

// AddLinkToCache indicates an expected call of AddLinkToCache.
func (mr *MockTripRepositoryMockRecorder) AddLinkToCache(ctx, uuid, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLinkToCache", reflect.TypeOf((*MockTripRepository)(nil).AddLinkToCache), ctx, uuid, id)
}

// AddTrip mocks base method.
func (m *MockTripRepository) AddTrip(ctx context.Context, value *models.Trip, userID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrip", ctx, value, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTrip indicates an expected call of AddTrip.
func (mr *MockTripRepositoryMockRecorder) AddTrip(ctx, value, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrip", reflect.TypeOf((*MockTripRepository)(nil).AddTrip), ctx, value, userID)
}

// AddTripUser mocks base method.
func (m *MockTripRepository) AddTripUser(ctx context.Context, tripId, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTripUser", ctx, tripId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTripUser indicates an expected call of AddTripUser.
func (mr *MockTripRepositoryMockRecorder) AddTripUser(ctx, tripId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTripUser", reflect.TypeOf((*MockTripRepository)(nil).AddTripUser), ctx, tripId, userId)
}

// AlbumsByUser mocks base method.
func (m *MockTripRepository) AlbumsByUser(ctx context.Context, id int) (*[]models.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlbumsByUser", ctx, id)
	ret0, _ := ret[0].(*[]models.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlbumsByUser indicates an expected call of AlbumsByUser.
func (mr *MockTripRepositoryMockRecorder) AlbumsByUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlbumsByUser", reflect.TypeOf((*MockTripRepository)(nil).AlbumsByUser), ctx, id)
}

// CheckLink mocks base method.
func (m *MockTripRepository) CheckLink(ctx context.Context, uuid string, id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLink", ctx, uuid, id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckLink indicates an expected call of CheckLink.
func (mr *MockTripRepositoryMockRecorder) CheckLink(ctx, uuid, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLink", reflect.TypeOf((*MockTripRepository)(nil).CheckLink), ctx, uuid, id)
}

// DeleteAlbum mocks base method.
func (m *MockTripRepository) DeleteAlbum(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlbum", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlbum indicates an expected call of DeleteAlbum.
func (mr *MockTripRepositoryMockRecorder) DeleteAlbum(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlbum", reflect.TypeOf((*MockTripRepository)(nil).DeleteAlbum), ctx, id)
}

// DeleteTrip mocks base method.
func (m *MockTripRepository) DeleteTrip(ctx context.Context, id int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrip", ctx, id)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTrip indicates an expected call of DeleteTrip.
func (mr *MockTripRepositoryMockRecorder) DeleteTrip(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrip", reflect.TypeOf((*MockTripRepository)(nil).DeleteTrip), ctx, id)
}

// GetAlbumAuthor mocks base method.
func (m *MockTripRepository) GetAlbumAuthor(ctx context.Context, id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumAuthor", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumAuthor indicates an expected call of GetAlbumAuthor.
func (mr *MockTripRepositoryMockRecorder) GetAlbumAuthor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumAuthor", reflect.TypeOf((*MockTripRepository)(nil).GetAlbumAuthor), ctx, id)
}

// GetAlbumById mocks base method.
func (m *MockTripRepository) GetAlbumById(ctx context.Context, id int) (*models.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumById", ctx, id)
	ret0, _ := ret[0].(*models.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumById indicates an expected call of GetAlbumById.
func (mr *MockTripRepositoryMockRecorder) GetAlbumById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumById", reflect.TypeOf((*MockTripRepository)(nil).GetAlbumById), ctx, id)
}

// GetTripAuthors mocks base method.
func (m *MockTripRepository) GetTripAuthors(ctx context.Context, id int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripAuthors", ctx, id)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripAuthors indicates an expected call of GetTripAuthors.
func (mr *MockTripRepositoryMockRecorder) GetTripAuthors(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripAuthors", reflect.TypeOf((*MockTripRepository)(nil).GetTripAuthors), ctx, id)
}

// GetTripById mocks base method.
func (m *MockTripRepository) GetTripById(ctx context.Context, id int) (*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripById", ctx, id)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripById indicates an expected call of GetTripById.
func (mr *MockTripRepositoryMockRecorder) GetTripById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripById", reflect.TypeOf((*MockTripRepository)(nil).GetTripById), ctx, id)
}

// GetTripsByUser mocks base method.
func (m *MockTripRepository) GetTripsByUser(ctx context.Context, id int) (*[]models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripsByUser", ctx, id)
	ret0, _ := ret[0].(*[]models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripsByUser indicates an expected call of GetTripsByUser.
func (mr *MockTripRepositoryMockRecorder) GetTripsByUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripsByUser", reflect.TypeOf((*MockTripRepository)(nil).GetTripsByUser), ctx, id)
}

// SightsByTrip mocks base method.
func (m *MockTripRepository) SightsByTrip(ctx context.Context, id int) (*[]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SightsByTrip", ctx, id)
	ret0, _ := ret[0].(*[]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SightsByTrip indicates an expected call of SightsByTrip.
func (mr *MockTripRepositoryMockRecorder) SightsByTrip(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SightsByTrip", reflect.TypeOf((*MockTripRepository)(nil).SightsByTrip), ctx, id)
}

// UpdateAlbum mocks base method.
func (m *MockTripRepository) UpdateAlbum(ctx context.Context, id int, album *models.Album) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlbum", ctx, id, album)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAlbum indicates an expected call of UpdateAlbum.
func (mr *MockTripRepositoryMockRecorder) UpdateAlbum(ctx, id, album interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlbum", reflect.TypeOf((*MockTripRepository)(nil).UpdateAlbum), ctx, id, album)
}

// UpdateTrip mocks base method.
func (m *MockTripRepository) UpdateTrip(ctx context.Context, id int, value *models.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrip", ctx, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrip indicates an expected call of UpdateTrip.
func (mr *MockTripRepositoryMockRecorder) UpdateTrip(ctx, id, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrip", reflect.TypeOf((*MockTripRepository)(nil).UpdateTrip), ctx, id, value)
}
