version: '3.7'
services:
  auth_service:
    build:
      dockerfile: Dockerfile.auth_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "10123:10123"
    environment:
      - USER_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - USER_GRPC_PORT=10123
      - USER_PREFIX_LEN=0
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  sight_service:
    build:
      dockerfile: Dockerfile.sight_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "10124:10124"
    environment:
      - SIGHT_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - SIGHT_GRPC_PORT=10124
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  trip_service:
    build:
      dockerfile: Dockerfile.trip_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "6666:6666"
    environment:
      - TRIP_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - TRIP_GRPC_PORT=6666
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  gateway:
    depends_on:
      - trip_service
      - auth_service
    build:
      dockerfile: Dockerfile.gateway
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_HTTP_PORT=:8080
      - GATEWAY_AUTH_ENDPOINT=host.docker.internal:10123
      - GATEWAY_TRIP_ENDPOINT=host.docker.internal:6666
      - GATEWAY_SIGHT_ENDPOINT=host.docker.internal:10124
    extra_hosts:
      - "host.docker.internal:172.17.0.1"


