version: '3.7'
services:
  auth_service:
    image: znajderko/snake/auth_service
    build:
      dockerfile: Dockerfile.auth_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "10123:10123"
      - "11123:8080"
    environment:
      - USER_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - USER_GRPC_PORT=10123
      - USER_PREFIX_LEN=3
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  sight_service:
    image: znajderko/snake/sight_service
    build:
      dockerfile: Dockerfile.sight_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "10124:10124"
      - "11124:8080"
    environment:
      - SIGHT_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - SIGHT_GRPC_PORT=10124
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  trip_service:
    image: znajderko/snake/trip_service
    build:
      dockerfile: Dockerfile.trip_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "6666:6666"
      - "16666:8080"
    environment:
      - TRIP_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - TRIP_GRPC_PORT=6666
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  review_service:
    image: znajderko/snake/review_service
    build:
      dockerfile: Dockerfile.review_service
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "9090:9090"
      - "19090:8080"
    environment:
      - REVIEW_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - REVIEW_GRPC_PORT=9090
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  gateway:
    image: znajderko/snake/gateway
    depends_on:
      - trip_service
      - auth_service
      - sight_service
      - review_service
    build:
      dockerfile: Dockerfile.gateway
      context: .
      args:
        - APP_PKG_NAME=snakealive/m
        - GOOS=linux
    ports:
      - "8080:8081"
      - "18080:8080"
    environment:
      - GATEWAY_HTTP_PORT=:8081
      - GATEWAY_AUTH_ENDPOINT=host.docker.internal:10123
      - GATEWAY_TRIP_ENDPOINT=host.docker.internal:6666
      - GATEWAY_SIGHT_ENDPOINT=host.docker.internal:10124
      - GATEWAY_REVIEW_ENDPOINT=host.docker.internal:9090
      - GATEWAY_DB_URL=postgres://tripadvisor:12345@host.docker.internal:5432/tripadvisor
      - GATEWAY_S3_BUCKET=snakehastrip
      - GATEWAY_S3_ENDPOINT=http://hb.bizmrg.com
      - GATEWAY_S3_PUBLIC_ENDPOINT=https://snakehastrip.hb.bizmrg.com/
      - GATEWAY_S3_SECRET_KEY=7qdqBBT9xeKDV3iAdKco4jqEhmjpMqiyk3bLL9PcU2S7
      - GATEWAY_S3_SECRET_ID=
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    profiles: [ "monitoring" ]
    image: prom/node-exporter:latest
    restart: unless-stopped
    ports:
      - "9100:9100"

  grafana:
    profiles: [ "monitoring" ]
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3010"

