// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pkg/services/sight/api.proto

package sight_service

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country     string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Rating      float32  `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Tags        []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Description string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Photos      []string `protobuf:"bytes,7,rep,name=photos,proto3" json:"photos,omitempty"`
}

func (x *Sight) Reset() {
	*x = Sight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sight) ProtoMessage() {}

func (x *Sight) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sight.ProtoReflect.Descriptor instead.
func (*Sight) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{0}
}

func (x *Sight) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sight) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sight) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Sight) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Sight) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Sight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Sight) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

type GetSightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName string `protobuf:"bytes,1,opt,name=countryName,proto3" json:"countryName,omitempty"`
}

func (x *GetSightsRequest) Reset() {
	*x = GetSightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsRequest) ProtoMessage() {}

func (x *GetSightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsRequest.ProtoReflect.Descriptor instead.
func (*GetSightsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetSightsRequest) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

type GetSightsReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sights []*Sight `protobuf:"bytes,1,rep,name=sights,proto3" json:"sights,omitempty"`
}

func (x *GetSightsReponse) Reset() {
	*x = GetSightsReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsReponse) ProtoMessage() {}

func (x *GetSightsReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsReponse.ProtoReflect.Descriptor instead.
func (*GetSightsReponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetSightsReponse) GetSights() []*Sight {
	if x != nil {
		return x.Sights
	}
	return nil
}

type GetSightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSightRequest) Reset() {
	*x = GetSightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightRequest) ProtoMessage() {}

func (x *GetSightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightRequest.ProtoReflect.Descriptor instead.
func (*GetSightRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetSightRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sight *Sight `protobuf:"bytes,1,opt,name=sight,proto3" json:"sight,omitempty"`
}

func (x *GetSightResponse) Reset() {
	*x = GetSightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightResponse) ProtoMessage() {}

func (x *GetSightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightResponse.ProtoReflect.Descriptor instead.
func (*GetSightResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetSightResponse) GetSight() *Sight {
	if x != nil {
		return x.Sight
	}
	return nil
}

var File_pkg_services_sight_api_proto protoreflect.FileDescriptor

var file_pkg_services_sight_api_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73,
	0x69, 0x67, 0x68, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x05, 0x53, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x0b, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0xfa, 0x42, 0x07, 0x72, 0x05, 0x18, 0x80, 0x01, 0x20, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x73, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x22, 0x2a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67,
	0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x05, 0x73, 0x69, 0x67, 0x68, 0x74, 0x32, 0xd2, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x68,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x12, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d,
	0x73, 0x6e, 0x61, 0x6b, 0x65, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x6d, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x69, 0x67, 0x68, 0x74, 0x3b,
	0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_services_sight_api_proto_rawDescOnce sync.Once
	file_pkg_services_sight_api_proto_rawDescData = file_pkg_services_sight_api_proto_rawDesc
)

func file_pkg_services_sight_api_proto_rawDescGZIP() []byte {
	file_pkg_services_sight_api_proto_rawDescOnce.Do(func() {
		file_pkg_services_sight_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_services_sight_api_proto_rawDescData)
	})
	return file_pkg_services_sight_api_proto_rawDescData
}

var file_pkg_services_sight_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_services_sight_api_proto_goTypes = []interface{}{
	(*Sight)(nil),            // 0: services.sight_service.Sight
	(*GetSightsRequest)(nil), // 1: services.sight_service.GetSightsRequest
	(*GetSightsReponse)(nil), // 2: services.sight_service.GetSightsReponse
	(*GetSightRequest)(nil),  // 3: services.sight_service.GetSightRequest
	(*GetSightResponse)(nil), // 4: services.sight_service.GetSightResponse
}
var file_pkg_services_sight_api_proto_depIdxs = []int32{
	0, // 0: services.sight_service.GetSightsReponse.sights:type_name -> services.sight_service.Sight
	0, // 1: services.sight_service.GetSightResponse.sight:type_name -> services.sight_service.Sight
	1, // 2: services.sight_service.SightService.GetSights:input_type -> services.sight_service.GetSightsRequest
	3, // 3: services.sight_service.SightService.GetSight:input_type -> services.sight_service.GetSightRequest
	2, // 4: services.sight_service.SightService.GetSights:output_type -> services.sight_service.GetSightsReponse
	4, // 5: services.sight_service.SightService.GetSight:output_type -> services.sight_service.GetSightResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_services_sight_api_proto_init() }
func file_pkg_services_sight_api_proto_init() {
	if File_pkg_services_sight_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_services_sight_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_services_sight_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_services_sight_api_proto_goTypes,
		DependencyIndexes: file_pkg_services_sight_api_proto_depIdxs,
		MessageInfos:      file_pkg_services_sight_api_proto_msgTypes,
	}.Build()
	File_pkg_services_sight_api_proto = out.File
	file_pkg_services_sight_api_proto_rawDesc = nil
	file_pkg_services_sight_api_proto_goTypes = nil
	file_pkg_services_sight_api_proto_depIdxs = nil
}
