// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: pkg/services/sight/api.proto

package sight_service

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Sight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country     string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Rating      float32  `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Tags        []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Description string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Photos      []string `protobuf:"bytes,7,rep,name=photos,proto3" json:"photos,omitempty"`
	Lat         float32  `protobuf:"fixed32,8,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng         float32  `protobuf:"fixed32,9,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *Sight) Reset() {
	*x = Sight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sight) ProtoMessage() {}

func (x *Sight) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sight.ProtoReflect.Descriptor instead.
func (*Sight) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{1}
}

func (x *Sight) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sight) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sight) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Sight) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Sight) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Sight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Sight) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Sight) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Sight) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type GetSightsByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetSightsByIDsRequest) Reset() {
	*x = GetSightsByIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsByIDsRequest) ProtoMessage() {}

func (x *GetSightsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetSightsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetSightsByIDsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetSightsByIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sights []*Sight `protobuf:"bytes,1,rep,name=sights,proto3" json:"sights,omitempty"`
}

func (x *GetSightsByIDsResponse) Reset() {
	*x = GetSightsByIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsByIDsResponse) ProtoMessage() {}

func (x *GetSightsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetSightsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetSightsByIDsResponse) GetSights() []*Sight {
	if x != nil {
		return x.Sights
	}
	return nil
}

type GetSightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName string `protobuf:"bytes,1,opt,name=countryName,proto3" json:"countryName,omitempty"`
}

func (x *GetSightsRequest) Reset() {
	*x = GetSightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsRequest) ProtoMessage() {}

func (x *GetSightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsRequest.ProtoReflect.Descriptor instead.
func (*GetSightsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetSightsRequest) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

type GetSightsReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sights []*Sight `protobuf:"bytes,1,rep,name=sights,proto3" json:"sights,omitempty"`
}

func (x *GetSightsReponse) Reset() {
	*x = GetSightsReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsReponse) ProtoMessage() {}

func (x *GetSightsReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsReponse.ProtoReflect.Descriptor instead.
func (*GetSightsReponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetSightsReponse) GetSights() []*Sight {
	if x != nil {
		return x.Sights
	}
	return nil
}

type GetSightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSightRequest) Reset() {
	*x = GetSightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightRequest) ProtoMessage() {}

func (x *GetSightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightRequest.ProtoReflect.Descriptor instead.
func (*GetSightRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetSightRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sight *Sight `protobuf:"bytes,1,opt,name=sight,proto3" json:"sight,omitempty"`
}

func (x *GetSightResponse) Reset() {
	*x = GetSightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightResponse) ProtoMessage() {}

func (x *GetSightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightResponse.ProtoReflect.Descriptor instead.
func (*GetSightResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetSightResponse) GetSight() *Sight {
	if x != nil {
		return x.Sight
	}
	return nil
}

type SearchSightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search     string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Skip       int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit      int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Countries  []string `protobuf:"bytes,4,rep,name=countries,proto3" json:"countries,omitempty"`
	Tags       []int64  `protobuf:"varint,5,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	MinReviews int64    `protobuf:"varint,6,opt,name=minReviews,proto3" json:"minReviews,omitempty"`
	MinRating  int64    `protobuf:"varint,7,opt,name=minRating,proto3" json:"minRating,omitempty"`
}

func (x *SearchSightRequest) Reset() {
	*x = SearchSightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchSightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSightRequest) ProtoMessage() {}

func (x *SearchSightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSightRequest.ProtoReflect.Descriptor instead.
func (*SearchSightRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{8}
}

func (x *SearchSightRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchSightRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *SearchSightRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSightRequest) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *SearchSightRequest) GetTags() []int64 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchSightRequest) GetMinReviews() int64 {
	if x != nil {
		return x.MinReviews
	}
	return 0
}

func (x *SearchSightRequest) GetMinRating() int64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

type SearchSightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sights []*Sight `protobuf:"bytes,1,rep,name=sights,proto3" json:"sights,omitempty"`
}

func (x *SearchSightResponse) Reset() {
	*x = SearchSightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchSightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSightResponse) ProtoMessage() {}

func (x *SearchSightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSightResponse.ProtoReflect.Descriptor instead.
func (*SearchSightResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{9}
}

func (x *SearchSightResponse) GetSights() []*Sight {
	if x != nil {
		return x.Sights
	}
	return nil
}

type GetSightsByTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag int64 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetSightsByTagRequest) Reset() {
	*x = GetSightsByTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsByTagRequest) ProtoMessage() {}

func (x *GetSightsByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsByTagRequest.ProtoReflect.Descriptor instead.
func (*GetSightsByTagRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetSightsByTagRequest) GetTag() int64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type GetSightsByTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sights []*Sight `protobuf:"bytes,1,rep,name=sights,proto3" json:"sights,omitempty"`
}

func (x *GetSightsByTagResponse) Reset() {
	*x = GetSightsByTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSightsByTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSightsByTagResponse) ProtoMessage() {}

func (x *GetSightsByTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSightsByTagResponse.ProtoReflect.Descriptor instead.
func (*GetSightsByTagResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetSightsByTagResponse) GetSights() []*Sight {
	if x != nil {
		return x.Sights
	}
	return nil
}

type GetTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{12}
}

type GetTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_services_sight_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_sight_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_sight_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_pkg_services_sight_api_proto protoreflect.FileDescriptor

var file_pkg_services_sight_api_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73,
	0x69, 0x67, 0x68, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x05, 0x53, 0x69, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6c, 0x6e, 0x67, 0x22, 0x29, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22,
	0x4f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x22, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05,
	0x18, 0x80, 0x01, 0x20, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52,
	0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x2a, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x05, 0x73, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x05, 0x73, 0x69, 0x67,
	0x68, 0x74, 0x22, 0xd8, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x12, 0x1d,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x4c, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x06, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x4f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x42, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73,
	0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x67,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x32, 0xe5, 0x05, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x68, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x12, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x12, 0x2d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42,
	0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69,
	0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x2a,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x2d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x79, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x61, 0x67, 0x73, 0x12, 0x26, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73,
	0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f,
	0x5a, 0x2d, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x6d, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x69, 0x67, 0x68,
	0x74, 0x3b, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_services_sight_api_proto_rawDescOnce sync.Once
	file_pkg_services_sight_api_proto_rawDescData = file_pkg_services_sight_api_proto_rawDesc
)

func file_pkg_services_sight_api_proto_rawDescGZIP() []byte {
	file_pkg_services_sight_api_proto_rawDescOnce.Do(func() {
		file_pkg_services_sight_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_services_sight_api_proto_rawDescData)
	})
	return file_pkg_services_sight_api_proto_rawDescData
}

var file_pkg_services_sight_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_services_sight_api_proto_goTypes = []interface{}{
	(*Tag)(nil),                    // 0: services.sight_service.Tag
	(*Sight)(nil),                  // 1: services.sight_service.Sight
	(*GetSightsByIDsRequest)(nil),  // 2: services.sight_service.GetSightsByIDsRequest
	(*GetSightsByIDsResponse)(nil), // 3: services.sight_service.GetSightsByIDsResponse
	(*GetSightsRequest)(nil),       // 4: services.sight_service.GetSightsRequest
	(*GetSightsReponse)(nil),       // 5: services.sight_service.GetSightsReponse
	(*GetSightRequest)(nil),        // 6: services.sight_service.GetSightRequest
	(*GetSightResponse)(nil),       // 7: services.sight_service.GetSightResponse
	(*SearchSightRequest)(nil),     // 8: services.sight_service.SearchSightRequest
	(*SearchSightResponse)(nil),    // 9: services.sight_service.SearchSightResponse
	(*GetSightsByTagRequest)(nil),  // 10: services.sight_service.GetSightsByTagRequest
	(*GetSightsByTagResponse)(nil), // 11: services.sight_service.GetSightsByTagResponse
	(*GetTagsRequest)(nil),         // 12: services.sight_service.GetTagsRequest
	(*GetTagsResponse)(nil),        // 13: services.sight_service.GetTagsResponse
}
var file_pkg_services_sight_api_proto_depIdxs = []int32{
	1,  // 0: services.sight_service.GetSightsByIDsResponse.sights:type_name -> services.sight_service.Sight
	1,  // 1: services.sight_service.GetSightsReponse.sights:type_name -> services.sight_service.Sight
	1,  // 2: services.sight_service.GetSightResponse.sight:type_name -> services.sight_service.Sight
	1,  // 3: services.sight_service.SearchSightResponse.sights:type_name -> services.sight_service.Sight
	1,  // 4: services.sight_service.GetSightsByTagResponse.sights:type_name -> services.sight_service.Sight
	0,  // 5: services.sight_service.GetTagsResponse.tags:type_name -> services.sight_service.Tag
	4,  // 6: services.sight_service.SightService.GetSights:input_type -> services.sight_service.GetSightsRequest
	6,  // 7: services.sight_service.SightService.GetSight:input_type -> services.sight_service.GetSightRequest
	2,  // 8: services.sight_service.SightService.GetSightsByIDs:input_type -> services.sight_service.GetSightsByIDsRequest
	8,  // 9: services.sight_service.SightService.SearchSights:input_type -> services.sight_service.SearchSightRequest
	10, // 10: services.sight_service.SightService.GetSightsByTag:input_type -> services.sight_service.GetSightsByTagRequest
	12, // 11: services.sight_service.SightService.GetTags:input_type -> services.sight_service.GetTagsRequest
	12, // 12: services.sight_service.SightService.GetRandomTags:input_type -> services.sight_service.GetTagsRequest
	5,  // 13: services.sight_service.SightService.GetSights:output_type -> services.sight_service.GetSightsReponse
	7,  // 14: services.sight_service.SightService.GetSight:output_type -> services.sight_service.GetSightResponse
	3,  // 15: services.sight_service.SightService.GetSightsByIDs:output_type -> services.sight_service.GetSightsByIDsResponse
	9,  // 16: services.sight_service.SightService.SearchSights:output_type -> services.sight_service.SearchSightResponse
	11, // 17: services.sight_service.SightService.GetSightsByTag:output_type -> services.sight_service.GetSightsByTagResponse
	13, // 18: services.sight_service.SightService.GetTags:output_type -> services.sight_service.GetTagsResponse
	13, // 19: services.sight_service.SightService.GetRandomTags:output_type -> services.sight_service.GetTagsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_services_sight_api_proto_init() }
func file_pkg_services_sight_api_proto_init() {
	if File_pkg_services_sight_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_services_sight_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsByIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsByIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchSightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchSightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsByTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSightsByTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_services_sight_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_services_sight_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_services_sight_api_proto_goTypes,
		DependencyIndexes: file_pkg_services_sight_api_proto_depIdxs,
		MessageInfos:      file_pkg_services_sight_api_proto_msgTypes,
	}.Build()
	File_pkg_services_sight_api_proto = out.File
	file_pkg_services_sight_api_proto_rawDesc = nil
	file_pkg_services_sight_api_proto_goTypes = nil
	file_pkg_services_sight_api_proto_depIdxs = nil
}
