prometheus:
  image: prom/prometheus
  ports:
    - "9000:9090"
  volumes:
    - ./monitoring/prometheus:/etc/prometheus
  command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

node-exporter:
  image: prom/node-exporter:latest
  restart: unless-stopped
  ports:
    - "9100:9100"

grafana:
  image: grafana/grafana:latest
  volumes:
    - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
  ports:
    - "3000:3010"