name: tripadvisor deploy

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: lsla
        run: ls -la
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_TOKEN }}
      - name: Build gateway and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gateway:latest
          target: Dockerfile.gateway
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: whoami && docker-compose --version

