name: tripadvisor deploy

on:
  pull_request:
    branches: [ main, develop, pre-develop ]
  push:
    branches: [ main, develop, pre-develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: whoami && docker-compose --version

