name: tripadvisor deploy

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: vendor
        run: go mod vendor
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_TOKEN }}

      - name: build && push docker image
        env:
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_ID: ${{ secrets.S3_ID }}
          PSQL_CONN: ${{ secrets.PSQL_CONN }}
        run: echo $PSQL_CONN && cd deploy && docker-compose build && docker-compose push

      - name: running latest service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.PATH }} &&
            docker-compose stop &&
            docker-compose rm -f &&
            docker-compose pull &&
            docker-compose up -d


