name: tripadvisor prepare

on:
  pull_request:
    branches: [ main, develop, pre-develop ]
  push:
    branches: [ main, develop, pre-develop ]

permissions:
  contents: read
  pull-requests: read

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go vet ./...
      - run: go fmt ./...


  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go test ./...

